# Generated by Django 6.0.4 on 2026-04-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body_part', models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('core', 'Core'), ('cardio', 'Cardio'), ('other', 'Other')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('initial_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fees_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('one_time_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight_lifted_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.exercise')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='accounts.memberprofile')),
            ],
            options={
                'ordering': ['-date', 'exercise__name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.memberprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateField()),
                ('month_paid_for', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.memberprofile')),
            ],
            options={
                'ordering': ['-payment_date'],
                'unique_together': {('member', 'month_paid_for')},
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='accounts.memberprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
