# Generated by Django 5.0.4 on 2026-05-12 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Monthly Fee', 'Monthly Fee'), ('Deposit', 'One-Time Deposit'), ('Other', 'Other')], default='Monthly Fee', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month_paid_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('title', models.CharField(help_text="E.g., 'Weight Loss Plan (April)'", max_length=150)),
                ('breakfast', models.TextField(blank=True)),
                ('lunch', models.TextField(blank=True)),
                ('dinner', models.TextField(blank=True)),
                ('snacks', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or guidelines.')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='accounts.memberprofile')),
            ],
            options={
                'ordering': ['-date_assigned'],
            },
        ),
    ]
