# Generated by Django 5.0.4 on 2026-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
