# Generated by Django 5.0.4 on 2026-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberprofile_has_changed_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Monthly Fee', 'Monthly Fee'), ('Deposit', 'One-Time Deposit'), ('Other', 'Other')], default='Monthly Fee', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month_paid_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
