# Generated by Django 5.0.4 on 2026-04-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_payment_unique_together_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('title', models.CharField(help_text="E.g., 'Weight Loss Plan (April)'", max_length=150)),
                ('breakfast', models.TextField(blank=True)),
                ('lunch', models.TextField(blank=True)),
                ('dinner', models.TextField(blank=True)),
                ('snacks', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or guidelines.')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='accounts.memberprofile')),
            ],
            options={
                'ordering': ['-date_assigned'],
            },
        ),
    ]
